name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install make
        run: sudo apt install make sqlite3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.0' 
      
      - name: Install dependencies
        run: go mod download
      
      - name: Make Builds
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          files: |
            build/*.zip